services:
    db:
        build: .
        environment:
            POSTGRES_PASSWORD: root_event_password
        volumes:
            - pgdata:/var/lib/postgresql/data
            - pgtablespaces:/var/lib/pg_tablespaces
            - ./init_scripts:/docker-entrypoint-initdb.d
        ports:
            - 5432:5432

volumes:
    pgdata:
    pgtablespaces:
