services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: event_user
            POSTGRES_PASSWORD: event_password
            POSTGRES_DB: event_database
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    pgdata:
